export type FindingSeverity = "info" | "warn" | "fail" | "blocking";

export type FindingCode =
  | "TEST_SKIPPED"
  | "TEST_DELETED"
  | "TEST_WEAKENED"
  | "DEPENDENCY_FILE_CHANGED"
  | "LOCKFILE_CHANGED"
  | "LOCAL_ARTIFACT_INCLUDED"
  | "NO_ACTIVE_SESSION"
  | "SCOPE_EXPANSION_WARN"
  | "MISSING_IMPLEMENTATION_CHANGE"
  | "PLAN_TOO_VAGUE"
  | "MISSING_TEST_STRATEGY"
  | "GIT_UNAVAILABLE"
  | "CI_FILE_CHANGED"
  | "SECRET_FILE_CHANGED"
  | "SCOPE_LIMIT_EXCEEDED"
  | "APPROVAL_REQUIRED_PATH_CHANGED"
  | "BLOCKED_PATH_CHANGED"
  | "DEPENDENCY_CHANGE_INTENT"
  | "CI_CHANGE_INTENT"
  | "BROAD_REFACTOR_INTENT";
